config/routes.rb
Rails.application.routes.draw do
  get 'instruct/index'
  post 'instruct/test'

  resources :responses

  get 'disclosure/index'

  get 'welcome/index'
  root 'welcome#index'
 get 'done/index'
  

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/response.rb
class Response < ApplicationRecord
	validates :r1x1, :r1x2, :r1x3, :r2x1, :r2x2, :r2x3, :r3x1, :r3x2, :r3x3, :r4x1, :r4x2, :r4x3, :r5x1, :r5x2, :r5x3, :r6x1, :r6x2, :r6x3, :r7x1, :r7x2, :r7x3, :r8x1, :r8x2, :r8x3, :r9x1, :r9x2, :r9x3, :r10x1, :r10x2, :r10x3 , :r11x1, :r11x2, :r11x3, :r12x1, :r12x2, :r12x3 , :r13x1, :r13x2, :r13x3 , :r14x1, :r14x2, :r14x3 , :r15x1, :r15x2, :r15x3 , :r16x1, :r16x2, :r16x3 , :r17x1, :r17x2, :r17x3 , :r18x1, :r18x2, :r18x3 , :r19x1, :r19x2, :r19x3 , :r20x1, :r20x2, :r20x3, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/disclosure_controller.rb
class DisclosureController < ApplicationController
  def index
  	render layout: false
  end
end

app/controllers/done_controller.rb
class DoneController < ApplicationController
  def index
  	render layout: false
  	puts"done"
  end
end

app/controllers/instruct_controller.rb
class InstructController < ApplicationController
  def index

  end
  def test
  	
  	if params[:r1].to_i  > 60 and params[:r2].to_i  > 60 and params[:r3].to_i  > 60
  		puts "above"
  		redirect_to responses_url
  		
  	else
  		puts "below"
  		render inline: "location.reload();" 
  		flash[:danger] = 'These answers dont make sense try again.'
  	end
  end
end

app/controllers/responses_controller.rb
class ResponsesController < ApplicationController

  def index
  end

   def new
    @response = Response.new
  end

  

  # POST /responses
  # POST /responses.json
 
  def create
    @response = Response.new(response_params)
    
    if @response.save
        flash[:success] = 'Response sucessfully recorded.'
      	redirect_to done_index_url
    else
        
        flash[:danger] = 'There was a problem. Please fill out all fields.'
        render :index
        
  
   end
 end

  private
    # Use callbacks to share common setup or constraints between actions.
   

    # Never trust parameters from the scary internet, only allow the white list through.
    def response_params
      params.require(:response).permit(:r1x1, :r1x2, :r1x3, :r2x1, :r2x2, :r2x3, :r3x1, :r3x2, :r3x3, :r4x1, :r4x2, :r4x3, :r5x1, :r5x2, :r5x3, :r6x1, :r6x2, :r6x3, :r7x1, :r7x2, :r7x3, :r8x1, :r8x2, :r8x3, :r9x1, :r9x2, :r9x3, :r10x1, :r10x2, :r10x3 , :r11x1, :r11x2, :r11x3, :r12x1, :r12x2, :r12x3 , :r13x1, :r13x2, :r13x3 , :r14x1, :r14x2, :r14x3 , :r15x1, :r15x2, :r15x3 , :r16x1, :r16x2, :r16x3 , :r17x1, :r17x2, :r17x3 , :r18x1, :r18x2, :r18x3 , :r19x1, :r19x2, :r19x3 , :r20x1, :r20x2, :r20x3)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  		render layout: false
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/disclosure_helper.rb
module DisclosureHelper
end

app/helpers/instruct_helper.rb
module InstructHelper
end

app/helpers/responses_helper.rb
module ResponsesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/disclosure/index.html.erb
<!DOCTYPE html>
<html>
  <head>
<title>Aggregation Experiment</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>

    <%= render 'shared/navigation' %>

    <div id="main-container" class="container">
      <div class="row">
        <div class="col-xs-12">
          <% flash.each do |name, msg| -%>
            <%= content_tag :div, msg, class: "alert alert-#{name}" %>
          <% end -%>
        </div>
      </div>

        <div class="row">
        <div class="col-xs-2 ">
        </div>
        <div class="col-xs-8 align-items-center">
         
		  <h3>Implied Consent to Participate in Research</h3>

<br> The purpose of this research is to understand the relationship between writing styles and personality. The researcher, Henry Boswell, is a researcher at San Francisco State University and is conducting research in the Psychology department. 

<h3>This is a pilot study. </h3>
<br> The results of this study will not be shared or disseminated for publication or made available to others outside the organization associated with the research.<br>

<br> Compensation for participating in this research will be $ 0.25 The survey should take approximately 5 minutes to complete. <br>

<br> PARTICIPATION IN THIS RESEARCH IS VOLUNTARY. You may choose to participate or not. If you do not wish to participate, you may simply log out with no penalty to yourself. If you do participate, your participation in the survey indicates your consent to the above conditions. <br>
         

        </div>
    </div>
    <div class="actions lead mid">

     <p class="lead">
             
              <%= link_to 'Take Survey' , instruct_index_url, class: 'btn btn-lg btn-secondary' %>

            </p> 
  </div>


     
        
          <%= yield %>

       
    
    </div>
    
<%= render 'shared/footer' %>
  </body>

  <style>
  .btn-secondary:focus {
  color: #333;
  text-shadow: none; /* Prevent inheritance from `body` */
  background-color: #fff;
  border: .05rem solid #fff;
}
/* You could choose to override all browser styles on all your inputs, but I prefer explicit classes */
body {
  background: #fff;
  font-size: 14px;
  font-family: "Times New Roman", Times, serif;
  text-rendering: optimizeLegibility;
  color: #444;
}


/* GET RID OF LABELS */

.value label {
  display: none;
}


/* STYLE LABEL TD  */

td.label {
  font-weight: 700;
  padding-right: 1em;
}


/* STYLE VALUE RADIO TD */

.value::before {
  /* content: 'Colour'; */
  display: block;
  float: left;
  margin: 10px 15px 0 0;
}


/* RADIO */

.value input[type="radio"] {
  position: relative;
  width: 26px;
  height: 26px;
  cursor: pointer;

}


/* HIDE THE FIRST RADIO GENERATED FROM SELECT OPTIONS */

.value input[type="radio"]:first-child {
  display: none;
}


/* TOP COLOR BLOCK */

input[type="radio"]:before {

  position: absolute;
  content: "";
  top: 0px;
  left: 0px;
  width: 24px;
  height: 24px;
  border: 1px solid #dddddd;
  z-index: 2;
}


/* BG COLOR BLOCK */

input[type="radio"]:after {
  border: 1px solid #dddddd;
  background: #fff;
  position: absolute;
  content: "";
  width: 24px;
  height: 24px;
  z-index: 1;
}
.footer {
   position:absolute;
    /* Height of the footer */
   
}


/* HOVER */

input[type="radio"]:hover:after {
  /* border-color: #000; */
  background: black;
}


/* CHECKED STATES */

.value input[type="radio"]:checked:after {
  //border: 1px solid #000;
  content: '';
  display: block;
  width: 24px;
  height: 24px;
  background-color: black;
  background: red;
}

.value input[type="radio"]:checked:hover:after {
  background: black;
}


/* COLORED ATTRIBUTES */

.value input[type="radio"][value="black"]:before {
  
}

.value input[type="radio"][value="white"]:before {
 background: white;
}

.value input[type="radio"][value="red"]:before {
  background: red;
}


h3{
  text-align: center;
}


.align-items-center{

border: 1px solid black;
text-align: center;

}

.mid{
	text-align: center;
}
.textcolor{
  color: black;

}

/* Extra markup and styles for table-esque vertical and horizontal centering */
.site-wrapper {
  padding-top: 50px;
  text-align: center;
  display: table;
  width: 100%;
  height: 100%; /* For at least Firefox */
  min-height: 100%;
  
}
</style>
</html>

app/views/done/index.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
  	<meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    
    <title>Done</title>
    <%= stylesheet_link_tag 'application' %>
 
  </head>
  <div class="row">
        <div class="col-xs-12">
          <% flash.each do |name, msg| -%>
            <%= content_tag :div, msg, class: "alert alert-#{name}" %>
          <% end -%>
        </div>
      </div>

  <body>
    <div class="site-wrapper">
      <div class="site-wrapper-inner">
        <div class="cover-container">
          <div class="inner cover">
            <h1 class="cover-heading">Thank You</h1>
            <p class="lead">You are done.</p>
            <p class="lead">
             
             
            </p>
          </div>
          <div class="mastfoot">
            <div class="inner">
              <p>Data collection for a computer science project at SFSU</p>
            </div>
          </div>
        </div>
      </div>
    </body>

   
    
  
  <style>
/*
 * Globals
 */

/* Links */
a,
a:focus,
a:hover {
  color: #fff;
}

/* Custom default button */
.btn-secondary,
.btn-secondary:hover,
.btn-secondary:focus {
  color: #333;
  text-shadow: none; /* Prevent inheritance from `body` */
  background-color: #fff;
  border: .05rem solid #fff;
}


/*
 * Base structure
 */

html,
body {
  height: 100%;
  background-color: #330033;
}
body {
  color: #fff;
  text-align: center;
  text-shadow: 0 .05rem .1rem rgba(0,0,0,.5);
}

/* Extra markup and styles for table-esque vertical and horizontal centering */
.site-wrapper {
  display: table;
  width: 100%;
  height: 100%; /* For at least Firefox */
  min-height: 100%;
  -webkit-box-shadow: inset 0 0 5rem rgba(0,0,0,.5);
          box-shadow: inset 0 0 5rem rgba(0,0,0,.5);
}
.site-wrapper-inner {
  display: table-cell;
  vertical-align: top;
}
.cover-container {
  margin-right: auto;
  margin-left: auto;
}

/* Padding for spacing */
.inner {
  padding: 2rem;
}


/*
 * Header
 */

.masthead {
  margin-bottom: 2rem;
}

.masthead-brand {
  margin-bottom: 0;
}

.nav-masthead .nav-link {
  padding: .25rem 0;
  font-weight: bold;
  color: rgba(255,255,255,.5);
  background-color: transparent;
  border-bottom: .25rem solid transparent;
}

.nav-masthead .nav-link:hover,
.nav-masthead .nav-link:focus {
  border-bottom-color: rgba(255,255,255,.25);
}

.nav-masthead .nav-link + .nav-link {
  margin-left: 1rem;
}

.nav-masthead .active {
  color: #fff;
  border-bottom-color: #fff;
}

@media (min-width: 48em) {
  .masthead-brand {
    float: left;
  }
  .nav-masthead {
    float: right;
  }
}


/*
 * Cover
 */

.cover {
  padding: 0 1.5rem;
}
.cover .btn-lg {
  padding: .75rem 1.25rem;
  font-weight: bold;
}


/*
 * Footer
 */

.mastfoot {
  color: rgba(255,255,255,.5);
}


/*
 * Affix and center
 */

@media (min-width: 40em) {
  /* Pull out the header and footer */
  .masthead {
    position: fixed;
    top: 0;
  }
  .mastfoot {
    position: fixed;
    bottom: 0;
  }
  /* Start the vertical centering */
  .site-wrapper-inner {
    vertical-align: middle;
  }
  /* Handle the widths */
  .masthead,
  .mastfoot,
  .cover-container {
    width: 100%; /* Must be percentage or pixels for horizontal alignment */
  }
}

@media (min-width: 62em) {
  .masthead,
  .mastfoot,
  .cover-container {
    width: 42rem;
  }
}
n-left: 40px;
} 
</style>
</html>

app/views/instruct/_object1.html.erb
METALLIC

app/views/instruct/_object2.html.erb
CONTAINER

app/views/instruct/index.html.erb
<%= form_with url: instruct_test_url do |form| %>


  <table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">Object</th>
      <th scope="col"><%= render 'object1' %></th>
      <th scope="col"><%= render 'object2' %></th>
      <th scope="col"><%= render 'object1' %> and <%= render 'object2' %></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th scope="row">Bucket</th>
      <td><%= form.text_field :r1, id: :response_r1, size: "6x12"%></td></td>
      <td><%= form.text_field :r2, id: :response_r2, size: "6x12"%></td></td>
      <td><%= form.text_field :r3, id: :response_r3, size: "6x12"%></td>
    </tr>
     </tbody>
</table>


<style>
.actions {
  padding-top: 50px;
  text-align: center;
  

  
}


</style>
  <div class="actions">
    <%= form.submit "Submit", class: "btn btn-success" %>
  </div>
<% end %>

   
 
<style>
.footer {
   position:absolute;
    /* Height of the footer */
   
}
</style>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
<title>Visual</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>

    <%= render 'shared/navigation' %>

    <div id="main-container" class="container">
      <div class="row">
        <div class="col-xs-12">
          <% flash.each do |name, msg| -%>
            <%= content_tag :div, msg, class: "alert alert-#{name}" %>
          <% end -%>
        </div>
      </div>

        <%= render 'shared/instructions' %>


     
        
          <%= yield %>
       
    
    </div>
<%= render 'shared/footer' %>
  </body>
</html>

app/views/responses/_object1.html.erb
METALLIC

app/views/responses/_object2.html.erb
CONTAINER

app/views/responses/index.html.erb
<%= form_for Response.new do |form| %>

 <table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">Object</th>
      <th scope="col"><%= render 'object1' %></th>
      <th scope="col"><%= render 'object2' %></th>
      <th scope="col"><%= render 'object1' %> and <%= render 'object2' %></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th scope="row">Bag</th>
      <td><%= form.text_field :r1x1, size: "6x12"%></td></td>
      <td><%= form.text_field :r1x2,  size: "6x12"%></td></td>
      <td><%= form.text_field :r1x3,  size: "6x12"%></td>
    </tr>
     <tr>
      <th scope="row">Baking Sheet</th>
      <td><%= form.text_field :r2x1, size: "6x12"%></td></td>
      <td><%= form.text_field :r2x2,  size: "6x12"%></td></td>
      <td><%= form.text_field :r2x3,  size: "6x12"%></td>
    </tr>
     <tr>
      <th scope="row">Ball Point Pen</th>
      <td><%= form.text_field :r3x1, size: "6x12"%></td></td>
      <td><%= form.text_field :r3x2,  size: "6x12"%></td></td>
      <td><%= form.text_field :r3x3,  size: "6x12"%></td>
    </tr>
     <tr>
      <th scope="row">Bath Tub</th>
      <td><%= form.text_field :r4x1, size: "6x12"%></td></td>
      <td><%= form.text_field :r4x2,  size: "6x12"%></td></td>
      <td><%= form.text_field :r4x3,  size: "6x12"%></td>
    </tr>
     <tr>
      <th scope="row">Book Cover</th>
      <td><%= form.text_field :r5x1, size: "6x12"%></td></td>
      <td><%= form.text_field :r5x2,  size: "6x12"%></td></td>
      <td><%= form.text_field :r5x3,  size: "6x12"%></td>
    </tr>
     <tr>
      <th scope="row">Car</th>
      <td><%= form.text_field :r6x1, size: "6x12"%></td></td>
      <td><%= form.text_field :r6x2,  size: "6x12"%></td></td>
      <td><%= form.text_field :r6x3,  size: "6x12"%></td>
    </tr>
     <tr>
      <th scope="row">Cash Register</th>
      <td><%= form.text_field :r7x1, size: "6x12"%></td></td>
      <td><%= form.text_field :r7x2,  size: "6x12"%></td></td>
      <td><%= form.text_field :r7x3,  size: "6x12"%></td>
    </tr>
     <tr>
      <th scope="row">Container</th>
      <td><%= form.text_field :r8x1, size: "6x12"%></td></td>
      <td><%= form.text_field :r8x2,  size: "6x12"%></td></td>
      <td><%= form.text_field :r8x3,  size: "6x12"%></td>
    </tr>
     <tr>
      <th scope="row">Fridge</th>
      <td><%= form.text_field :r9x1, size: "6x12"%></td></td>
      <td><%= form.text_field :r9x2,  size: "6x12"%></td></td>
      <td><%= form.text_field :r9x3,  size: "6x12"%></td>
    </tr>
     <tr>
      <th scope="row">Hollywood Swing</th>
      <td><%= form.text_field :r10x1, size: "6x12"%></td></td>
      <td><%= form.text_field :r10x2,  size: "6x12"%></td></td>
      <td><%= form.text_field :r10x3,  size: "6x12"%></td>
    </tr>
    <tr>
      <th scope="row">Kerosene Lamp</th>
      <td><%= form.text_field :r11x1, size: "6x12"%></td></td>
      <td><%= form.text_field :r11x2,  size: "6x12"%></td></td>
      <td><%= form.text_field :r11x3,  size: "6x12"%></td>
    </tr>
    <tr>
      <th scope="row">Mail</th>
      <td><%= form.text_field :r12x1, size: "6x12"%></td></td>
      <td><%= form.text_field :r12x2,  size: "6x12"%></td></td>
      <td><%= form.text_field :r12x3,  size: "6x12"%></td>
    </tr>
    <tr>
      <th scope="row">Parking Meter</th>
      <td><%= form.text_field :r13x1, size: "6x12"%></td></td>
      <td><%= form.text_field :r13x2,  size: "6x12"%></td></td>
      <td><%= form.text_field :r13x3,  size: "6x12"%></td>
    </tr>
    <tr>
      <th scope="row">Baby Carriage</th>
      <td><%= form.text_field :r14x1, size: "6x12"%></td></td>
      <td><%= form.text_field :r14x2,  size: "6x12"%></td></td>
      <td><%= form.text_field :r14x3,  size: "6x12"%></td>
    </tr>
    <tr>
      <th scope="row">Coffee Press</th>
      <td><%= form.text_field :r15x1, size: "6x12"%></td></td>
      <td><%= form.text_field :r15x2,  size: "6x12"%></td></td>
      <td><%= form.text_field :r15x3,  size: "6x12"%></td>
    </tr>
    <tr>
      <th scope="row">Shovel</th>
      <td><%= form.text_field :r16x1, size: "6x12"%></td></td>
      <td><%= form.text_field :r16x2,  size: "6x12"%></td></td>
      <td><%= form.text_field :r16x3,  size: "6x12"%></td>
    </tr>
    <tr>
      <th scope="row">Silver Spoon</th>
      <td><%= form.text_field :r17x1, size: "6x12"%></td></td>
      <td><%= form.text_field :r17x2,  size: "6x12"%></td></td>
      <td><%= form.text_field :r17x3,  size: "6x12"%></td>
    </tr>
    <tr>
      <th scope="row">Sledge Hammer</th>
      <td><%= form.text_field :r18x1, size: "6x12"%></td></td>
      <td><%= form.text_field :r18x2,  size: "6x12"%></td></td>
      <td><%= form.text_field :r18x3,  size: "6x12"%></td>
    </tr>
    <tr>
      <th scope="row">Water Bottle</th>
      <td><%= form.text_field :r19x1, size: "6x12"%></td></td>
      <td><%= form.text_field :r19x2,  size: "6x12"%></td></td>
      <td><%= form.text_field :r19x3,  size: "6x12"%></td>
    </tr>
    <tr>
      <th scope="row">Wine Barrel</th>
      <td><%= form.text_field :r20x1, size: "6x12"%></td></td>
      <td><%= form.text_field :r20x2,  size: "6x12"%></td></td>
      <td><%= form.text_field :r20x3,  size: "6x12"%></td>
    </tr>
    
   </tbody>
</table>


<style>
.actions {
  padding-top: 50px;
  text-align: center;
  
  
}

</style>
  <div class="actions">
    <%= form.submit "Submit", class: "btn btn-success" %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer">
  <small>
   
  </small>
  <nav class = "footer">
   
  </nav>
</footer>


<style>
  /* footer */

.footer {
  margin-top: 45px;
  padding-top: 5px;
  color: #777;
  background-color: #330033;
}





footer small {
  float: left;
}

footer ul {
  float: right;
  list-style: none;
}

footer ul li {
  float: left;
  margin-left: 15px;
}
.footer {

   bottom:0;
   width:100%;
   height:60px;   /* Height of the footer */
   
}
</style>

app/views/shared/_instructions.html.erb
<div class="row">
        <div class="col-xs-2 ">
        </div>
        <div class="col-xs-8 align-items-center">
          <h3>Evaulating Objects</h3>
          <ul>
          	
  			<li>In the table below you will find the names of some objects.</li>
  			<li> Please select the grade to which you consider each object to be.
        <li> the catagories are as follows: <%= render 'object1' %>, a <%= render 'object2' %>, or a <%= render 'object1' %>  <%= render 'object2' %></li>
        <li>Please, give a number between 0% and 100%.</li>
        <li>0% means: The object in question is NOT <%= render 'object1' %>, a <%= render 'object2' %>, or <%= render 'object1' %> and <%= render 'object2' %></li>
        <li>100% means: The object in question is 100% <%= render 'object1' %>, a <%= render 'object2' %>, or  <%= render 'object1' %> and <%= render 'object2' %></li>
        	
		  </ul>
         

        </div>
    </div>








<style>

h3{
  text-align: center;
}
body {
 
  text-align: left;
}
.row {
  padding-top: 10px;
  padding-bottom: 30px;

  
  
}

.align-items-center{

border: 1px solid black;

}

/* Extra markup and styles for table-esque vertical and horizontal centering */
.site-wrapper {
  padding-top: 50px;
  text-align: center;
  display: table;
  width: 100%;
  height: 100%; /* For at least Firefox */
  min-height: 100%;
  
}
</style>

app/views/shared/_navigation.html.erb
<!-- app/views/shared/_navigation.html.erb -->

<nav class="navbar navbar-default" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <a class="navbar-brand" href="/">Aggregation Study - San Francisco State University</a>
    </div>
  </div>
</nav>

<style>



.navbar{
background-color: #330033;


}

.navbar-default .navbar-brand {
color: #FFCC33;
}


</style>

app/views/welcome/index.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
  	<meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    
    <title>Aggregation Experiment</title>
    <%= stylesheet_link_tag 'application' %>
 
  </head>
  <div class="row">
        <div class="col-xs-12">
          <% flash.each do |name, msg| -%>
            <%= content_tag :div, msg, class: "alert alert-#{name}" %>
          <% end -%>
        </div>
      </div>

  <body>
    <div class="site-wrapper">
      <div class="site-wrapper-inner">
        <div class="cover-container">
          <div class="inner cover">
            <h1 class="cover-heading">Help us learn how human mind works.</h3>
            <p class="lead">This questionnaire is designed to gather data about the way a human mind aggregates inputs. It will take less than 5 minutes of your time. Thank you!</p>
            <p class="lead">
             
              <%= link_to 'Take Survey' , disclosure_index_url, class: 'btn btn-lg btn-secondary' %>

            </p>
            
          </div>
          <div class="mastfoot">
            <div class="inner">
              <p>Data Collection for  SFSU Computer Science</p>
            </div>
          </div>
        </div>
      </div>
    </body>

   
    
  
  <style>
/*
 * Globals
 */

/* Links */
a,
a:focus,
a:hover {
  color: #fff;
}

/* Custom default button */
.btn-secondary,
.btn-secondary:hover,
.btn-secondary:focus {
  color: #333;
  text-shadow: none; /* Prevent inheritance from `body` */
  background-color: #fff;
  border: .05rem solid #fff;
}


/*
 * Base structure
 */

html,
body {
  height: 100%;
  background-color: #330033;
}
body {
  color: #fff;
  text-align: center;
  text-shadow: 0 .05rem .1rem rgba(0,0,0,.5);
}

/* Extra markup and styles for table-esque vertical and horizontal centering */
.site-wrapper {
  display: table;
  width: 100%;
  height: 100%; /* For at least Firefox */
  min-height: 100%;
  -webkit-box-shadow: inset 0 0 5rem rgba(0,0,0,.5);
          box-shadow: inset 0 0 5rem rgba(0,0,0,.5);
}
.site-wrapper-inner {
  display: table-cell;
  vertical-align: top;
}
.cover-container {
  margin-right: auto;
  margin-left: auto;
}

/* Padding for spacing */
.inner {
  padding: 2rem;
}


/*
 * Header
 */

.masthead {
  margin-bottom: 2rem;
}

.masthead-brand {
  margin-bottom: 0;
}

.nav-masthead .nav-link {
  padding: .25rem 0;
  font-weight: bold;
  color: rgba(255,255,255,.5);
  background-color: transparent;
  border-bottom: .25rem solid transparent;
}

.nav-masthead .nav-link:hover,
.nav-masthead .nav-link:focus {
  border-bottom-color: rgba(255,255,255,.25);
}

.nav-masthead .nav-link + .nav-link {
  margin-left: 1rem;
}

.nav-masthead .active {
  color: #fff;
  border-bottom-color: #fff;
}

@media (min-width: 48em) {
  .masthead-brand {
    float: left;
  }
  .nav-masthead {
    float: right;
  }
}


/*
 * Cover
 */

.cover {
  padding: 0 1.5rem;
}
.cover .btn-lg {
  padding: .75rem 1.25rem;
  font-weight: bold;
}


/*
 * Footer
 */

.mastfoot {
  color: rgba(255,255,255,.5);
}


/*
 * Affix and center
 */

@media (min-width: 40em) {
  /* Pull out the header and footer */
  .masthead {
    position: fixed;
    top: 0;
  }
  .mastfoot {
    position: fixed;
    bottom: 0;
  }
  /* Start the vertical centering */
  .site-wrapper-inner {
    vertical-align: middle;
  }
  /* Handle the widths */
  .masthead,
  .mastfoot,
  .cover-container {
    width: 100%; /* Must be percentage or pixels for horizontal alignment */
  }
}

@media (min-width: 62em) {
  .masthead,
  .mastfoot,
  .cover-container {
    width: 42rem;
  }
}
n-left: 40px;
} 
</style>
</html>